<?php
	//application details
		$apps[$x]['name'] = "Feature Codes";
		$apps[$x]['guid'] = '52653013-2769-E013-28FA-EF2050D325ED';
		$apps[$x]['category'] = 'PBX';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
		$apps[$x]['description']['en'] = 'Used Configure feature codes. ';

	//menu details
		$apps[$x]['menu'][0]['title']['en'] = 'Feature Codes';
		$apps[$x]['menu'][0]['guid'] = '52653013-AB5C-C486-D71C-EF2050D325ED';
		$apps[$x]['menu'][0]['parent_guid'] = 'BC96D773-EE57-0CDD-C3AC-2D91ABA61B55';
		$apps[$x]['menu'][0]['category'] = 'internal';
		$apps[$x]['menu'][0]['path'] = '/mod/feature_codes/index.php';
		$apps[$x]['menu'][0]['groups'][] = 'admin';
		$apps[$x]['menu'][0]['groups'][] = 'superadmin';

	//permission details
		$apps[$x]['permissions'][0]['name'] = 'feature_codes_view';
		$apps[$x]['permissions'][0]['groups'][] = 'admin';
		$apps[$x]['permissions'][0]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][1]['name'] = 'feature_codes_add';
		$apps[$x]['permissions'][1]['groups'][] = 'admin';
		$apps[$x]['permissions'][1]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][2]['name'] = 'feature_codes_edit';
		$apps[$x]['permissions'][2]['groups'][] = 'admin';
		$apps[$x]['permissions'][2]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][3]['name'] = 'feature_codes_delete';
		$apps[$x]['permissions'][3]['groups'][] = 'admin';
		$apps[$x]['permissions'][3]['groups'][] = 'superadmin';

	//schema details
		$y = 0;
		$apps[$x]['db'][0]['table'] = 'v_feature_codes';
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_code_id';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_code';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_type';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_id';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_table';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_edit_link';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_delete_link';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_label';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_xml';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'feature_display';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		
	// put the table creation for lua dialplan in here for now
		$y = 0;
		$apps[$x]['db'][$z]['table'] = 'v_dialplan_lua_routes';
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_route_id';
		$apps[$x]['db'][$z]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$z]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'v_domain';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'dialed_number';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_field';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_table';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_type';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'ring_seconds';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'ring_type';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'music_on_hold';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'enabled';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;	
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'name';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'description';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_order';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'caller_route_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'time_route_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';		
		$z++;
		
		$y = 0;
		$apps[$x]['db'][$z]['table'] = 'v_dialplan_lua_caller_routes';
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'id';
		$apps[$x]['db'][$z]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$z]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;			
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'caller_route_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'enabled';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'cid_prefix';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'name';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'description';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_order';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$z++;
		
		
	// dialplan_lua stuff...
		$y = 0;
		$apps[$x]['db'][$z]['table'] = 'v_dialplan_lua_time_routes';
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'id';
		$apps[$x]['db'][$z]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$z]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;			
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'time_group';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'name';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'description';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'start_hour';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'start_minute';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'start_second';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'end_hour';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'end_minute';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'end_second';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'days_week';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'days_month';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'months';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'years';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_order';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$z++;

/*	put actions in LUA script */
/*		$y = 0;
		$apps[$x]['db'][$z]['table'] = 'v_dialplan_lua_actions';
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'id';
		$apps[$x]['db'][$z]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$z]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_action_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;		
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'application';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'data';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][$z]['fields'][$y]['name'] = 'lua_order';
		$apps[$x]['db'][$z]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][$z]['fields'][$y]['description'] = '';
*/
?>
