#!/bin/bash
rm -rf /usr/src/fusionpbx-dev
rm -rf /usr/src/debs-fusionpbx-dev

svn export http://fusionpbx.googlecode.com/svn/branches/dev/fusionpbx /usr/src/fusionpbx-dev

cp -rp /root/my-scripts/debian-dev /usr/src/fusionpbx-dev/debian

cd /usr/src/fusionpbx-dev

dpkg-buildpackage -rfakeroot -i

cd /usr/src

mkdir -p debs-fusionpbx-dev

mv *.changes debs-fusionpbx-dev
mv *.deb debs-fusionpbx-dev
mv *.dsc debs-fusionpbx-dev
mv *.gz debs-fusionpbx-dev

cd /root

cp -r /usr/src/debs-fusionpbx-dev/* /home/apt/incoming

import-new-pkgs.sh
